[app]
title = BP Tracker
package.name = bptracker
package.domain = org.bptracker
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,md,db
version = 1.0
requirements = python3,kivy
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.3.1
fullscreen = 0
android.api = 34
android.minapi = 21
android.gradle_dependencies = 
android.gradle_api_references = 
android.sdk = 34
android.ndk = 25b
android.arch = arm64-v8a
android.entitlements = 
android.add_src = 
android.permissions = WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
android.extra_java_deps = 
android.add_jars = 
android.accept_sdk_license = True
android.manifest_intent_filters = 
android.allow_download_prebuilder = True
android.allow_download_ndk = True
android.allow_download_sdk = True
android.allow_download_ant = True
android.allow_download_gradle = True
android.allow_download_apache_ant = True
android.private_storage_path = 
android.copy_libs = 
android.native_libs = 
android.wakelock = False
android.window_class = 
android.window_flags = 
android.wakelock_timeout = 10000
android.background = False
android.background_color = 0xFFFFFF
android.enable_androidx = True
android.export_lint = False
android.fullscreen = 0
android.hide_status_bar = False
android.keep_screen_on = False
android.launch_mode = singleTop
android.log_lvl = 2
android.log_enable = True
android.port = 9999
android.presplash_color = #FFFFFF
android.presplash_fill_percentage = 100
android.resizeable = False
android.screen = full
android.screen_options = 
android.sdk_path = 
android.ndk_path = 
android.sdk_version = 
android.title = BP Tracker
android.use_sdl2 = True
android.window_size = 360x640
android.window_min_size = 360x640
android.window_title = BP Tracker
author = 
description = Blood Pressure Tracking App
icon = 
presplash = 
keywords = blood pressure, health, tracking
source.exclude = *.pyc,__pycache__,.git
log_level = 2
log_dir = ./.logs
requirements_ext = 

[buildozer]
log_level = 2
warn_on_root = 1
archive = 0
