name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --entrypoint /bin/bash

    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        run: |
          cd /__w/bp-tracker/bp-tracker
          rm -f blood_pressure.db
          echo y | buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bp-tracker-apk
          path: /__w/bp-tracker/bp-tracker/bin/*.apk
